
/* Note: auto generated by scripts. You should not edit this file. */
import { metadata as theArtOfReadableCodeMetaData } from "../posts/design/the-art-of-readable-code/page.mdx";
import { metadata as ajaxMetaData } from "../posts/tech/ajax/page.mdx";
import { metadata as asyncVsDeferMetaData } from "../posts/tech/async-vs-defer/page.mdx";
import { metadata as browserReflowVsRepaintMetaData } from "../posts/tech/browser-reflow-vs-repaint/page.mdx";
import { metadata as browserRenderingMechanismMetaData } from "../posts/tech/browser-rendering-mechanism/page.mdx";
import { metadata as corsMetaData } from "../posts/tech/cors/page.mdx";
import { metadata as frontendModuleDesignMetaData } from "../posts/tech/frontend-module-design/page.mdx";
import { metadata as generatorsAndAsyncProgrammingMetaData } from "../posts/tech/generators-and-async-programming/page.mdx";
import { metadata as gitEssentialOperationsMetaData } from "../posts/tech/git-essential-operations/page.mdx";
import { metadata as infiniteScrollMetaData } from "../posts/tech/infinite-scroll/page.mdx";
import { metadata as javascriptHandwrittenCodeExamplesMetaData } from "../posts/tech/javascript-handwritten-code-examples/page.mdx";
import { metadata as mvcMvpMvvmMetaData } from "../posts/tech/mvc-mvp-mvvm/page.mdx";
import { metadata as regxExecAndMatchMetaData } from "../posts/tech/regx-exec-and-match/page.mdx";
import { metadata as understandingScrollOffsetClientPropertiesMetaData } from "../posts/tech/understanding-scroll-offset-client-properties/page.mdx";
import { metadata as virtualScrollerMetaData } from "../posts/tech/virtual-scroller/page.mdx";
import { metadata as vscodeAutoCompletionPluginTutorialMetaData } from "../posts/tech/vscode-auto-completion-plugin-tutorial/page.mdx";
import { metadata as whyLearnNodejsMetaData } from "../posts/tech/why-learn-nodejs/page.mdx";
import { metadata as youKnowJavascriptMetaData } from "../posts/tech/you-know-javascript/page.mdx";
import { metadata as feynmanLearningMethodMetaData } from "../posts/think/feynman-learning-method/page.mdx";
import { metadata as generatingNewProductIdeasMetaData } from "../posts/think/generating-new-product-ideas/page.mdx";
import { metadata as howToSelfImprovementMetaData } from "../posts/think/how-to-self-improvement/page.mdx";
import { metadata as independentDeveloperStoriesMetaData } from "../posts/think/independent-developer-stories/page.mdx";
import { metadata as netflixAndRockstarsMetaData } from "../posts/think/netflix-and-rockstars/page.mdx";
import { metadata as productDesignGuideWritingBusinessPlanMetaData } from "../posts/think/product-design-guide-writing-business-plan/page.mdx";
import { metadata as thoughtsOnFrontendDeathDebateMetaData } from "../posts/think/thoughts-on-frontend-death-debate/page.mdx";
import { metadata as workRelatedReflectionsMetaData } from "../posts/think/work-related-reflections/page.mdx";

export const allPosts = [
  {
    url: '/posts/design/the-art-of-readable-code',
    metadata: theArtOfReadableCodeMetaData
  },
  {
    url: '/posts/tech/ajax',
    metadata: ajaxMetaData
  },
  {
    url: '/posts/tech/async-vs-defer',
    metadata: asyncVsDeferMetaData
  },
  {
    url: '/posts/tech/browser-reflow-vs-repaint',
    metadata: browserReflowVsRepaintMetaData
  },
  {
    url: '/posts/tech/browser-rendering-mechanism',
    metadata: browserRenderingMechanismMetaData
  },
  {
    url: '/posts/tech/cors',
    metadata: corsMetaData
  },
  {
    url: '/posts/tech/frontend-module-design',
    metadata: frontendModuleDesignMetaData
  },
  {
    url: '/posts/tech/generators-and-async-programming',
    metadata: generatorsAndAsyncProgrammingMetaData
  },
  {
    url: '/posts/tech/git-essential-operations',
    metadata: gitEssentialOperationsMetaData
  },
  {
    url: '/posts/tech/infinite-scroll',
    metadata: infiniteScrollMetaData
  },
  {
    url: '/posts/tech/javascript-handwritten-code-examples',
    metadata: javascriptHandwrittenCodeExamplesMetaData
  },
  {
    url: '/posts/tech/mvc-mvp-mvvm',
    metadata: mvcMvpMvvmMetaData
  },
  {
    url: '/posts/tech/regx-exec-and-match',
    metadata: regxExecAndMatchMetaData
  },
  {
    url: '/posts/tech/understanding-scroll-offset-client-properties',
    metadata: understandingScrollOffsetClientPropertiesMetaData
  },
  {
    url: '/posts/tech/virtual-scroller',
    metadata: virtualScrollerMetaData
  },
  {
    url: '/posts/tech/vscode-auto-completion-plugin-tutorial',
    metadata: vscodeAutoCompletionPluginTutorialMetaData
  },
  {
    url: '/posts/tech/why-learn-nodejs',
    metadata: whyLearnNodejsMetaData
  },
  {
    url: '/posts/tech/you-know-javascript',
    metadata: youKnowJavascriptMetaData
  },
  {
    url: '/posts/think/feynman-learning-method',
    metadata: feynmanLearningMethodMetaData
  },
  {
    url: '/posts/think/generating-new-product-ideas',
    metadata: generatingNewProductIdeasMetaData
  },
  {
    url: '/posts/think/how-to-self-improvement',
    metadata: howToSelfImprovementMetaData
  },
  {
    url: '/posts/think/independent-developer-stories',
    metadata: independentDeveloperStoriesMetaData
  },
  {
    url: '/posts/think/netflix-and-rockstars',
    metadata: netflixAndRockstarsMetaData
  },
  {
    url: '/posts/think/product-design-guide-writing-business-plan',
    metadata: productDesignGuideWritingBusinessPlanMetaData
  },
  {
    url: '/posts/think/thoughts-on-frontend-death-debate',
    metadata: thoughtsOnFrontendDeathDebateMetaData
  },
  {
    url: '/posts/think/work-related-reflections',
    metadata: workRelatedReflectionsMetaData
  }
]
